server.port=8080

# CircuitBreaker configuration (optional, default will still work)
resilience4j.circuitbreaker.instances.deliveryCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.deliveryCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.deliveryCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.deliveryCircuitBreaker.waitDurationInOpenState=5000
